/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplemanagersystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vikto
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    public Employees() {
        initComponents();
    }
    
    
    
    String driver ="MySQL (Connector/J driver) (1)";
    String url ="jdbc:mysql://localhost:3306/classicmodels?zeroDateTimeBehavior=convertToNull";
    String user ="root";
    String pass ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("classicmodels?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        employees_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM Employees_1 e");
        employees_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employees_1Query.getResultList();
        EmployeeImg = new javax.swing.JLabel();
        lblEmployeeNumber = new javax.swing.JLabel();
        txtEmployeeNumber = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblExtension = new javax.swing.JLabel();
        txtExtension = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblOfficeCode = new javax.swing.JLabel();
        txtOfficeCode = new javax.swing.JTextField();
        lblReportsTo = new javax.swing.JLabel();
        txtReportsTo = new javax.swing.JTextField();
        lblJobTitle = new javax.swing.JLabel();
        txtJobTitle = new javax.swing.JTextField();
        lblemployeesList = new javax.swing.JLabel();
        txtemployeesList = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        tblEmployee = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeImg.setFont(new java.awt.Font("Segoe UI Black", 0, 100)); // NOI18N
        EmployeeImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\Untitled design.jpg")); // NOI18N
        EmployeeImg.setText("Employee");
        getContentPane().add(EmployeeImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 580, 150));

        lblEmployeeNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblEmployeeNumber.setText("EmployeeNumber");
        getContentPane().add(lblEmployeeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 30));

        txtEmployeeNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtEmployeeNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmployeeNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 190, 40));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblLastName.setText("LastName");
        getContentPane().add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, 30));

        txtLastName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 190, 40));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblFirstName.setText("FirstName");
        getContentPane().add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 190, -1));

        txtFirstName.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, 40));

        lblExtension.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblExtension.setText("Extension");
        getContentPane().add(lblExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 190, -1));

        txtExtension.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 190, 40));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 60, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 190, 40));

        lblOfficeCode.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblOfficeCode.setText("OfficeCode");
        getContentPane().add(lblOfficeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 30));

        txtOfficeCode.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtOfficeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficeCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtOfficeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 190, 40));

        lblReportsTo.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblReportsTo.setText("Reports To");
        getContentPane().add(lblReportsTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 200, 30));

        txtReportsTo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtReportsTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportsToActionPerformed(evt);
            }
        });
        getContentPane().add(txtReportsTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 190, 40));

        lblJobTitle.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblJobTitle.setText("JobTitle");
        getContentPane().add(lblJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 200, 30));

        txtJobTitle.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 190, 40));

        lblemployeesList.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblemployeesList.setText("EmployeesList");
        getContentPane().add(lblemployeesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        txtemployeesList.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtemployeesList, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 190, 40));

        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\1=.jpg")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 100, 100));

        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\edit.jpg")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 100, 100));

        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\delete.jpg")); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 100, 100));

        txtSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 210, 100));

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\serch.jpg")); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 550, 100, 100));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, employees_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${employeeNumber}"));
        columnBinding.setColumnName("Employee Number");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastName}"));
        columnBinding.setColumnName("Last Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstName}"));
        columnBinding.setColumnName("First Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${extension}"));
        columnBinding.setColumnName("Extension");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${officeCode}"));
        columnBinding.setColumnName("Office Code");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jobTitle}"));
        columnBinding.setColumnName("Job Title");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${employeesList}"));
        columnBinding.setColumnName("Employees List");
        columnBinding.setColumnClass(java.util.List.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${reportsTo}"));
        columnBinding.setColumnName("Reports To");
        columnBinding.setColumnClass(samplemanagersystem.Employees_1.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tblEmployee.setViewportView(jTable1);

        getContentPane().add(tblEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 660, 390));

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\lablewhite.png")); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtReportsToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportsToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportsToActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
    try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "insert into employees"
                +"(employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle)"
                +"values(?,?,?,?,?,?,?,?)";
        PreparedStatement pst =con.prepareStatement(sql);
        pst.setString(1, txtEmployeeNumber.getText());
        pst.setString(2, txtLastName.getText());
        pst.setString(3, txtFirstName.getText());
        pst.setString(4, txtExtension.getText());
        pst.setString(5, txtEmail.getText());
        pst.setString(6, txtOfficeCode.getText());
        pst.setString(7, txtReportsTo.getText());
        pst.setString(8, txtJobTitle.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Insert Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
      Update_table();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       
          try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "update employees set lastName=?,firstName=?,extension=?,email=?,officeCode=?,reportsTo=?,jobTitle=?  where employeeNumber=? ";
        PreparedStatement pst =con.prepareStatement(sql);
        
        pst.setString(1, txtLastName.getText());
        pst.setString(2, txtFirstName.getText());
        pst.setString(3, txtExtension.getText());
        pst.setString(4, txtEmail.getText());
        pst.setString(5, txtOfficeCode.getText());
        pst.setString(6, txtReportsTo.getText());
        pst.setString(7, txtJobTitle.getText());
        pst.setString(8, txtEmployeeNumber.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }  
        Update_table();
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtEmployeeNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNumberActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtOfficeCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficeCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeCodeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        
        try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Delete from employees  where employeeNumber=? ";
        PreparedStatement pst =con.prepareStatement(sql);
        
        
        pst.setString(1, txtEmployeeNumber.getText());
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Delete Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }  
        
        Update_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Employees().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeImg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private java.util.List<samplemanagersystem.Employees_1> employees_1List;
    private javax.persistence.Query employees_1Query;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeNumber;
    private javax.swing.JLabel lblExtension;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblJobTitle;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblOfficeCode;
    private javax.swing.JLabel lblReportsTo;
    private javax.swing.JLabel lblemployeesList;
    private javax.swing.JScrollPane tblEmployee;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeNumber;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtJobTitle;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOfficeCode;
    private javax.swing.JTextField txtReportsTo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtemployeesList;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void Update_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


 

    
 

}
