/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplemanagersystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vikto
 */
public class Offices extends javax.swing.JFrame {

    /**
     * Creates new form Offices
     */
    public Offices() {
        initComponents();
    }
    String driver ="MySQL (Connector/J driver) (1)";
    String url ="jdbc:mysql://localhost:3306/classicmodels?zeroDateTimeBehavior=convertToNull";
    String user ="root";
    String pass ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("classicmodels?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        offices_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT o FROM Offices_1 o");
        offices_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : offices_1Query.getResultList();
        OfficesImg = new javax.swing.JLabel();
        lblOfficeCode = new javax.swing.JLabel();
        txtOfficeCode = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddressLine1 = new javax.swing.JLabel();
        txtAddressLine1 = new javax.swing.JTextField();
        lblAddressLine2 = new javax.swing.JLabel();
        txtAddressLine2 = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        txtCountry = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        lblTerritory = new javax.swing.JLabel();
        txtTerritory = new javax.swing.JTextField();
        tblOffices = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(OfficesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lblOfficeCode.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblOfficeCode.setText("OfficeCode");
        getContentPane().add(lblOfficeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtOfficeCode.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtOfficeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 190, 40));

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblCity.setText("City");
        getContentPane().add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtCity.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, 40));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblPhone.setText("Phone");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        txtPhone.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, 40));

        lblAddressLine1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblAddressLine1.setText("AddressLine1");
        getContentPane().add(lblAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtAddressLine1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtAddressLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 190, 40));

        lblAddressLine2.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblAddressLine2.setText("AddressLine2");
        getContentPane().add(lblAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txtAddressLine2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressLine2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddressLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 190, 40));

        lblState.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblState.setText("State");
        getContentPane().add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        txtState.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });
        getContentPane().add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 190, 40));

        lblCountry.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblCountry.setText("Country");
        getContentPane().add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        txtCountry.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 190, 40));

        lblPostalCode.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblPostalCode.setText("PostalCode");
        getContentPane().add(lblPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        txtPostalCode.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtPostalCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 190, 40));

        lblTerritory.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblTerritory.setText("Territory");
        getContentPane().add(lblTerritory, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 90, 40));

        txtTerritory.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtTerritory, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 190, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, offices_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${officeCode}"));
        columnBinding.setColumnName("Office Code");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${city}"));
        columnBinding.setColumnName("City");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${phone}"));
        columnBinding.setColumnName("Phone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${addressLine1}"));
        columnBinding.setColumnName("Address Line1");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${addressLine2}"));
        columnBinding.setColumnName("Address Line2");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${state}"));
        columnBinding.setColumnName("State");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${country}"));
        columnBinding.setColumnName("Country");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${postalCode}"));
        columnBinding.setColumnName("Postal Code");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${territory}"));
        columnBinding.setColumnName("Territory");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tblOffices.setViewportView(jTable1);

        getContentPane().add(tblOffices, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 720, 390));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/1=.jpg"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 100, 100));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/edit.jpg"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 100, 100));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/delete.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 100, 100));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/serch.jpg"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 550, 100, 100));

        txtSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 250, 100));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressLine2ActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       
           try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "insert into offices"
                +"(officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory)"
                +"values(?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst =con.prepareStatement(sql);
        pst.setString(1, txtOfficeCode.getText());
        pst.setString(2, txtCity.getText());
        pst.setString(3, txtPhone.getText());
        pst.setString(4, txtAddressLine1.getText());
        pst.setString(5, txtAddressLine2.getText());
        pst.setString(6, txtState.getText());
        pst.setString(7, txtCountry.getText());
        pst.setString(8, txtPostalCode.getText());
        pst.setString(9, txtTerritory.getText());
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Insert Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        Update_table();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
            try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Update offices set city=?,phone=?,addressLine1=?,addressLine2=?,state=?,country=?,postalCode=?,territory=? where officeCode=?";
        PreparedStatement pst =con.prepareStatement(sql);
        
        pst.setString(1, txtCity.getText());
        pst.setString(2, txtPhone.getText());
        pst.setString(3, txtAddressLine1.getText());
        pst.setString(4, txtAddressLine2.getText());
        pst.setString(5, txtState.getText());
        pst.setString(6, txtCountry.getText());
        pst.setString(7, txtPostalCode.getText());
        pst.setString(8, txtTerritory.getText());
        pst.setString(9, txtOfficeCode.getText());
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
       Update_table(); 
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
          try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Delete from offices where officeCode=?";
        PreparedStatement pst =con.prepareStatement(sql);
        
        
        pst.setString(1, txtOfficeCode.getText());
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Delete Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        Update_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Offices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Offices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Offices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Offices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Offices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OfficesImg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblAddressLine2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblOfficeCode;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTerritory;
    private java.util.List<samplemanagersystem.Offices_1> offices_1List;
    private javax.persistence.Query offices_1Query;
    private javax.swing.JScrollPane tblOffices;
    private javax.swing.JTextField txtAddressLine1;
    private javax.swing.JTextField txtAddressLine2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtOfficeCode;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTerritory;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void Update_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
