/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplemanagersystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vikto
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
    }
    
    String driver ="MySQL (Connector/J driver) (1)";
    String url ="jdbc:mysql://localhost:3306/classicmodels?zeroDateTimeBehavior=convertToNull";
    String user ="root";
    String pass ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("classicmodels?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        orders_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT o FROM Orders_1 o");
        orders_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : orders_1Query.getResultList();
        OrdersImg = new javax.swing.JLabel();
        lblOrderNumber = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        lblOrderDate = new javax.swing.JLabel();
        txtOrderDate = new javax.swing.JTextField();
        lblRequiredDate = new javax.swing.JLabel();
        txtRequiredDate = new javax.swing.JTextField();
        lblShippedDate = new javax.swing.JLabel();
        txtShippedDate = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        lblComments = new javax.swing.JLabel();
        txtComments = new javax.swing.JTextField();
        lblCustomerNumber = new javax.swing.JLabel();
        txtCustomerNumber = new javax.swing.JTextField();
        tblOrders = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(OrdersImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        lblOrderNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblOrderNumber.setText("OrderNumber");
        getContentPane().add(lblOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        txtOrderNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 40));

        lblOrderDate.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblOrderDate.setText("OrderDate");
        getContentPane().add(lblOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        txtOrderDate.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 200, 40));

        lblRequiredDate.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblRequiredDate.setText("RequiredDate");
        getContentPane().add(lblRequiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        txtRequiredDate.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtRequiredDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, 40));

        lblShippedDate.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblShippedDate.setText("ShippedDate");
        getContentPane().add(lblShippedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        txtShippedDate.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtShippedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 200, 40));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblStatus.setText("Status");
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        txtStatus.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 200, 40));

        lblComments.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblComments.setText("Comments");
        getContentPane().add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        txtComments.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        txtComments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentsActionPerformed(evt);
            }
        });
        getContentPane().add(txtComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 200, 40));

        lblCustomerNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblCustomerNumber.setText("CustomerNumber");
        getContentPane().add(lblCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        txtCustomerNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 200, 40));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, orders_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${orderNumber}"));
        columnBinding.setColumnName("Order Number");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${orderDate}"));
        columnBinding.setColumnName("Order Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${requiredDate}"));
        columnBinding.setColumnName("Required Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${shippedDate}"));
        columnBinding.setColumnName("Shipped Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${comments}"));
        columnBinding.setColumnName("Comments");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${customerNumber}"));
        columnBinding.setColumnName("Customer Number");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tblOrders.setViewportView(jTable1);

        getContentPane().add(tblOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 690, 350));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/1=.jpg"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 100, 100));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/edit.jpg"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 100, 100));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/delete.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 100, 100));

        txtSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 240, 100));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/serch.jpg"))); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 100, 100));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    
            try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "insert into orders"
                +"(orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber)"
                +"values(?,?,?,?,?,?,?)";
        PreparedStatement pst =con.prepareStatement(sql);
        pst.setString(1, txtOrderNumber.getText());
        pst.setString(2, txtOrderDate.getText());
        pst.setString(3, txtRequiredDate.getText());
        pst.setString(4, txtShippedDate.getText());
        pst.setString(5, txtStatus.getText());
        pst.setString(6, txtComments.getText());
        pst.setString(7, txtCustomerNumber.getText());
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Insert Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        Update_table();
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Update orders set orderDate=?,requiredDate=?,shippedDate=?,status=?,comments=?,customerNumber=? where orderNumber=?";
        
        PreparedStatement pst =con.prepareStatement(sql);
      
        pst.setString(1, txtOrderDate.getText());
        pst.setString(2, txtRequiredDate.getText());
        pst.setString(3, txtShippedDate.getText());
        pst.setString(4, txtStatus.getText());
        pst.setString(5, txtComments.getText());
        pst.setString(6, txtCustomerNumber.getText());
        pst.setString(7, txtOrderNumber.getText());
        
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        
        Update_table();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
         try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Delete from orders where orderNumber=?";
        
        PreparedStatement pst =con.prepareStatement(sql);
      
        
        pst.setString(1, txtOrderNumber.getText());
        
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Delete Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        Update_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OrdersImg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblCustomerNumber;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblRequiredDate;
    private javax.swing.JLabel lblShippedDate;
    private javax.swing.JLabel lblStatus;
    private java.util.List<samplemanagersystem.Orders_1> orders_1List;
    private javax.persistence.Query orders_1Query;
    private javax.swing.JScrollPane tblOrders;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtCustomerNumber;
    private javax.swing.JTextField txtOrderDate;
    private javax.swing.JTextField txtOrderNumber;
    private javax.swing.JTextField txtRequiredDate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtShippedDate;
    private javax.swing.JTextField txtStatus;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void Update_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
