/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplemanagersystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vikto
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    public Payments() {
        initComponents();
    }
    String driver ="MySQL (Connector/J driver) (1)";
    String url ="jdbc:mysql://localhost:3306/classicmodels?zeroDateTimeBehavior=convertToNull";
    String user ="root";
    String pass ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentsImg = new javax.swing.JLabel();
        lblCustomerNumber = new javax.swing.JLabel();
        txtCustomerNumber = new javax.swing.JTextField();
        lblCheckNumber = new javax.swing.JLabel();
        txtCheckNumber = new javax.swing.JTextField();
        lblPaymentDate = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        tblPayments = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PaymentsImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        lblCustomerNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblCustomerNumber.setText("CustomerNumber");
        getContentPane().add(lblCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtCustomerNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtCustomerNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 190, 30));

        lblCheckNumber.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblCheckNumber.setText("CheckNumber");
        getContentPane().add(lblCheckNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        txtCheckNumber.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtCheckNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, 30));

        lblPaymentDate.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblPaymentDate.setText("PaymentDate");
        getContentPane().add(lblPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        txtPaymentDate.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 190, 30));

        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblAmount.setText("Amount");
        getContentPane().add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        txtAmount.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 190, 30));

        tblPayments.setViewportView(jTable1);

        getContentPane().add(tblPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 670, 330));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/1=.jpg"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 100, 100));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/edit.jpg"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 100, 100));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/delete.jpg"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 100, 100));

        txtSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 530, 210, 100));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java gui/serch.jpg"))); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, 100, 100));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        
        
            try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "insert into payments"
                +"(customerNumber,checkNumber,paymentDate,amount)"
                +"values(?,?,?,?)";
        PreparedStatement pst =con.prepareStatement(sql);
        pst.setString(1, txtCustomerNumber.getText());
        pst.setString(2, txtCheckNumber.getText());
        pst.setString(3, txtPaymentDate.getText());
        pst.setString(4, txtAmount.getText());
        
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Insert Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        Update_table();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
                 try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Update payments set checkNumber=?,paymentDate=?,amount=? where customerNumber=?";
        PreparedStatement pst =con.prepareStatement(sql);
        
        pst.setString(1, txtCheckNumber.getText());
        pst.setString(2, txtPaymentDate.getText());
        pst.setString(3, txtAmount.getText());
        pst.setString(4, txtCustomerNumber.getText());
        
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        Update_table();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Delete from payments where customerNumber=?";
        PreparedStatement pst =con.prepareStatement(sql);
        
        
        pst.setString(1, txtCustomerNumber.getText());
        
       
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Delete Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
       Update_table();  
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaymentsImg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCheckNumber;
    private javax.swing.JLabel lblCustomerNumber;
    private javax.swing.JLabel lblPaymentDate;
    private javax.swing.JScrollPane tblPayments;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCheckNumber;
    private javax.swing.JTextField txtCustomerNumber;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void Update_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
