/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplemanagersystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vikto
 */
public class ProductLines extends javax.swing.JFrame {

    /**
     * Creates new form ProductLines
     */
    public ProductLines() {
        initComponents();
    }
    String driver ="MySQL (Connector/J driver) (1)";
    String url ="jdbc:mysql://localhost:3306/classicmodels?zeroDateTimeBehavior=convertToNull";
    String user ="root";
    String pass ="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("classicmodels?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        productlines_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Productlines_1 p");
        productlines_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productlines_1Query.getResultList();
        ProductLinesImg = new javax.swing.JLabel();
        lblProductLine = new javax.swing.JLabel();
        txtProductLine = new javax.swing.JTextField();
        lblTextDescription = new javax.swing.JLabel();
        txtTextDescription = new javax.swing.JTextField();
        lblHtmlDescription = new javax.swing.JLabel();
        txtHtmlDescription = new javax.swing.JTextField();
        lblImage = new javax.swing.JLabel();
        txtImage = new javax.swing.JTextField();
        tblProductLines = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductLinesImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\Untitled design (4).jpg")); // NOI18N
        getContentPane().add(ProductLinesImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 810, 120));

        lblProductLine.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblProductLine.setText("ProductLine");
        getContentPane().add(lblProductLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txtProductLine.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtProductLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, 30));

        lblTextDescription.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblTextDescription.setText("TextDescription");
        getContentPane().add(lblTextDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtTextDescription.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtTextDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, 30));

        lblHtmlDescription.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblHtmlDescription.setText("HtmlDescription");
        getContentPane().add(lblHtmlDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtHtmlDescription.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtHtmlDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 210, 30));

        lblImage.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        lblImage.setText("Image");
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        txtImage.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        getContentPane().add(txtImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 210, 30));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, productlines_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productLine}"));
        columnBinding.setColumnName("Product Line");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${textDescription}"));
        columnBinding.setColumnName("Text Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${htmlDescription}"));
        columnBinding.setColumnName("Html Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${image}"));
        columnBinding.setColumnName("Image");
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tblProductLines.setViewportView(jTable1);

        getContentPane().add(tblProductLines, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 190, 680, 330));

        btnAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\1=.jpg")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 100, 100));

        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\edit.jpg")); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, 100, 100));

        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\delete.jpg")); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 100, 100));

        txtSearch.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 540, 220, 100));

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\serch.jpg")); // NOI18N
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 100, 100));

        lblBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\vikto\\Desktop\\java gui\\lablewhite.png")); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 660));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
          try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "insert into productlines"
                +"(productLine,textDescription,htmlDescription,image)"
                +"values(?,?,?,?)";
        PreparedStatement pst =con.prepareStatement(sql);
        pst.setString(1, txtProductLine.getText());
        pst.setString(2, txtTextDescription.getText());
        pst.setString(3, txtHtmlDescription.getText());
        pst.setString(4, txtImage.getText());
        
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Insert Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        Update_table();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Update productlines set textDescription=?,htmlDescription=?,image+? where productLine=?";
       
        PreparedStatement pst =con.prepareStatement(sql);
        
        pst.setString(1, txtTextDescription.getText());
        pst.setString(2, txtHtmlDescription.getText());
        pst.setString(3, txtImage.getText());
        pst.setString(4, txtProductLine.getText());
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Update Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        Update_table();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try
    {
   
        Connection con=DriverManager.getConnection(url, user, pass);
        String 
        
        sql = "Delete from  productlines  where productLine=?";
       
        PreparedStatement pst =con.prepareStatement(sql);
        
        
        pst.setString(1, txtProductLine.getText());
        
        
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Delete Successfully");
        
    }
        catch(HeadlessException | SQLException e)
        {
          JOptionPane.showMessageDialog(this, e.getMessage());  
        }
        
        Update_table();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductLines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductLines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProductLinesImg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblHtmlDescription;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblProductLine;
    private javax.swing.JLabel lblTextDescription;
    private java.util.List<samplemanagersystem.Productlines_1> productlines_1List;
    private javax.persistence.Query productlines_1Query;
    private javax.swing.JScrollPane tblProductLines;
    private javax.swing.JTextField txtHtmlDescription;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtProductLine;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTextDescription;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void Update_table() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
